import type { KnowledgeArticle } from "./knowledge";

export const additionalKnowledgeArticles: KnowledgeArticle[] = [
  {
    slug: "equipment-protection-levels-ga-gb-gc", title: "Equipment Protection Levels: Ga, Gb and Gc Explained", shortTitle: "EPL: Ga, Gb & Gc", category: "Hazardous areas",
    description: "Understand gas equipment protection levels Ga, Gb and Gc, their relationship to hazardous zones and why the complete Ex marking controls selection.",
    takeaways: ["How gas EPLs relate to zones", "Why IIC does not mean Zone 0", "Limits of a partial protection marking"],
    answer: "Ga, Gb and Gc identify equipment protection levels for explosive gas atmospheres. Ga provides a very high level of protection, Gb a high level and Gc an enhanced level. In the usual zone-based selection approach, Zone 0 calls for Ga, Zone 1 for Ga or Gb, and Zone 2 for Ga, Gb or Gc, subject to the installation requirements and certificate.",
    readMinutes: 5, updatedAt: "2026-09-16",
    sections: [
      { heading: "Read the level separately from the gas group", paragraphs: ["In an illustrative marking such as Ex db IIC T4 Gb, db identifies the flameproof protection level, IIC the gas subgroup, T4 the surface-temperature class and Gb the equipment protection level. Each addresses a different selection requirement. A demanding gas subgroup cannot compensate for an unsuitable EPL.", "That distinction matters when a product page lists several zones alongside IIC. An ordinary Ex db / Gb marking does not establish Zone 0 suitability. Use the complete certified marking rather than a marketing badge or the strength of the enclosure."] },
      { heading: "The usual gas-zone relationship", paragraphs: ["Zone classification describes the expected occurrence of an explosive atmosphere. EPL describes the protection provided by the equipment. The usual selection relationship is useful as a reference, but the project assessment and applicable installation rules can impose additional requirements."], bullets: ["Zone 0: Ga", "Zone 1: Ga or Gb", "Zone 2: Ga, Gb or Gc", "Gas EPLs must not be substituted for dust EPLs Da, Db and Dc"] },
      { heading: "Ex d is not always the complete marking", paragraphs: ["Modern flameproof markings distinguish protection levels such as da, db and dc. Their scope and conditions differ. Ex da has a restricted application scope and must not be inferred from a generic flameproof description. A certificate-supported Ga marking is needed before presenting a product as suitable for a Zone 0 application.", "For assemblies with several protection concepts, inspect the entire marking and certificate schedule. Intrinsically safe circuits, associated apparatus and equipment interfaces may have separate requirements; a fragment of the nameplate is insufficient."] },
      { heading: "A practical procurement check", paragraphs: ["Record the location's required EPL next to the proposed item's full marking in the equipment schedule. Check gas group, temperature class, ambient range and the certificate's covered configuration on the same line. This makes a mismatched zone declaration easier to identify before an order is placed.", "If the nameplate, web page and certificate disagree, request clarification for the exact type number and variant. Do not resolve the conflict by selecting whichever statement appears most permissive."] },
    ],
    faq: [{ question: "Does IIC mean an item is suitable for Zone 0?", answer: "No. IIC is a gas subgroup. The EPL and protection concept must separately support the required zone, and all other certificate conditions must match." }, { question: "Can Gb equipment be used in Zone 2?", answer: "Gb generally meets the gas EPL requirement for Zone 2, but the complete marking, certificate, ambient conditions and installation rules still have to be suitable." }],
    relatedProductCategory: "flameproof-junction-boxes",
    sources: [{ label: "IECEx protection techniques and EPL marking reference", url: "https://www.iecex.com/assets/Uploads/D2S2-Ex-Protection-Techniques-BARTEC.pdf" }],
  },
  {
    slug: "flamepaths-in-ex-d-enclosures", title: "Flamepaths in Ex d Enclosures: Function and Inspection", shortTitle: "Flamepaths & enclosure joints", category: "Protection concepts",
    description: "Learn how flamepaths help Ex d enclosures prevent flame transmission, which joints need attention and why repairs require the certified design and instructions.",
    takeaways: ["How controlled enclosure joints function", "What to inspect before reassembly", "Why generic repair dimensions are insufficient"],
    answer: "A flamepath is a controlled enclosure joint through which gases from an internal ignition may pass. Its certified geometry helps prevent transmission capable of igniting the external atmosphere. The joint may be a flanged face, spigot or threaded arrangement depending on the equipment design.",
    readMinutes: 5, updatedAt: "2026-09-16",
    sections: [
      { heading: "Why the joint is part of the protection", paragraphs: ["An Ex d enclosure is assessed as a complete construction that withstands an internal explosion and prevents its transmission to the surrounding explosive atmosphere. Covers, shafts and threaded entries can form controlled interfaces in that construction. Their dimensions and condition are functional features of the protection system.", "A flameproof enclosure is therefore more than a thick metal box. Replacing a cover, changing fasteners or adding an entry can alter the construction assessed by the certificate even if the modified assembly still looks mechanically robust."] },
      { heading: "Use the certified joint details", paragraphs: ["Permissible joint type, length, gap and thread engagement depend on the design, gas subgroup and applicable assessment. Do not use a generic internet table as permission to machine or repair a joint. Check the manufacturer's drawings, instructions and certificate conditions for the actual type number.", "An ingress seal and a flamepath have different functions. A gasket should not be assumed to provide the flameproof joint, and it must not be added or relocated in a way that changes the certified construction."] },
      { heading: "Inspection before reassembly", paragraphs: ["After the required isolation and safe-access procedure, competent personnel should inspect the assembly using the manufacturer's instructions and applicable inspection standard. Pay attention to the interfaces and parts that preserve the assessed construction."], bullets: ["Joint surfaces: damage, corrosion and foreign material", "Threads: condition and specified engagement", "Fasteners: correct type, completeness and tightening procedure", "Glands, adapters and stopping plugs: correct certified arrangement", "Covers, glass and operators: specified components and sound condition"] },
      { heading: "Escalate damage and unapproved changes", paragraphs: ["Do not file, sand, weld or machine a damaged flamepath as a routine cosmetic repair. Obtain a repair assessment based on the equipment documentation and the applicable repair requirements. Likewise, do not substitute bolts or drill new entries merely to simplify installation.", "Keep the inspection findings, type number and repair decision traceable to the item. If the certified construction cannot be established, escalate the equipment's continued use to the responsible hazardous-area engineer rather than relying on its appearance."] },
    ],
    faq: [{ question: "Can paint be applied to a flamepath?", answer: "Follow the manufacturer instructions and certified construction. Do not add coatings to controlled joint surfaces unless the documented arrangement permits them." }, { question: "Is the gasket always the flamepath?", answer: "No. Ingress seals and flameproof joints serve different functions. Identify the actual joint from the equipment design and instructions." }],
    relatedProductCategory: "flameproof-panels",
    sources: [{ label: "IECEx protection techniques reference", url: "https://www.iecex.com/assets/Uploads/D2S2-Ex-Protection-Techniques-BARTEC.pdf" }, { label: "IECEx installation and inspection reference", url: "https://www.iecex.com/assets/Uploads/D2S3-Installations.pdf" }],
  },
];
