import Link from "next/link";
import { notFound } from "next/navigation";
import { Edit, Printer } from "lucide-react";
import PurchaseOrderActions from "@/components/dashboard/purchase/order/PurchaseOrderActions";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { formatFinancialDocumentNumber } from "@/lib/helpers/globalHelpers/financialYear";
import { prisma } from "@/lib/prisma/db";
const money = (value: unknown) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR" }).format(Number(value));
export default async function PurchaseOrderDetailPage({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const order = await prisma.purchaseOrder.findUnique({ where: { id }, include: { items: { orderBy: { sortOrder: "asc" } }, goodsReceiptNotes: { select: { id: true, grnNo: true, grnFy: true, status: true } } } }); if (!order) notFound(); const poNumber = formatFinancialDocumentNumber(order.poFy, order.poNo); return <div className="space-y-6">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h1 className="text-2xl font-semibold">Purchase Order {poNumber}</h1><Badge variant={order.status === "CANCELLED" ? "destructive" : order.status === "DRAFT" ? "secondary" : "default"}>{order.status}</Badge></div><p className="text-sm text-muted-foreground">Created {order.createdAt.toLocaleString("en-IN")}{order.sentAt ? ` · Sent ${order.sentAt.toLocaleString("en-IN")}` : ""}</p></div><div className="flex flex-wrap gap-2">{order.status === "DRAFT" && <Button asChild><Link href={`/dashboard/purchase/orders/${id}/edit`}><Edit className="mr-2 h-4 w-4"/>Edit draft</Link></Button>}{order.status !== "DRAFT" && <Button variant="outline" asChild><Link target="_blank" href={`/purchase-orders/${id}`}><Printer className="mr-2 h-4 w-4"/>Print / PDF</Link></Button>}<PurchaseOrderActions id={id} status={order.status} supplierEmail={order.supplierEmail}/></div></div>
  <div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Supplier</CardTitle></CardHeader><CardContent className="space-y-1 text-sm"><div className="font-semibold">{order.supplierName}</div><div>{order.supplierAddress || "-"}</div><div>{order.supplierEmail || "-"} {order.supplierPhone ? `· ${order.supplierPhone}` : ""}</div><div>GSTIN: {order.supplierGstin || "-"}</div></CardContent></Card><Card><CardHeader><CardTitle>Order details</CardTitle></CardHeader><CardContent className="grid grid-cols-2 gap-3 text-sm"><div><span className="text-muted-foreground">Order date</span><div>{order.orderDate.toLocaleDateString("en-IN")}</div></div><div><span className="text-muted-foreground">Expected delivery</span><div>{order.expectedDate?.toLocaleDateString("en-IN") ?? "-"}</div></div><div><span className="text-muted-foreground">Payment terms</span><div>{order.paymentTerms || "-"}</div></div><div><span className="text-muted-foreground">Delivery terms</span><div>{order.deliveryTerms || "-"}</div></div></CardContent></Card></div>
  <Card><CardHeader><CardTitle>Materials</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>#</TableHead><TableHead>Material</TableHead><TableHead>HSN</TableHead><TableHead className="text-right">Qty</TableHead><TableHead className="text-right">Rate</TableHead><TableHead className="text-right">Disc.</TableHead><TableHead className="text-right">GST</TableHead><TableHead className="text-right">Total</TableHead></TableRow></TableHeader><TableBody>{order.items.map((item, index) => <TableRow key={item.id}><TableCell>{index + 1}</TableCell><TableCell><div className="font-medium">{item.title}</div><div className="text-xs text-muted-foreground">{item.itemCode}{item.remarks ? ` · ${item.remarks}` : ""}</div></TableCell><TableCell>{item.hsnCode || "-"}</TableCell><TableCell className="text-right">{Number(item.qty)} {item.unit}</TableCell><TableCell className="text-right">{money(item.unitPrice)}</TableCell><TableCell className="text-right">{Number(item.discountPercent)}%</TableCell><TableCell className="text-right">{Number(item.gstPercent)}%</TableCell><TableCell className="text-right font-medium">{money(item.lineTotal)}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
  <div className="grid gap-6 lg:grid-cols-[1fr_360px]"><Card><CardHeader><CardTitle>Delivery & terms</CardTitle></CardHeader><CardContent className="space-y-4 text-sm"><div><div className="text-muted-foreground">Ship to</div><div className="whitespace-pre-wrap">{order.shippingAddress || "-"}</div></div><div><div className="text-muted-foreground">Remarks</div><div>{order.remarks || "-"}</div></div><div><div className="text-muted-foreground">Terms</div><div className="whitespace-pre-wrap">{order.terms || "-"}</div></div>{order.goodsReceiptNotes.length > 0 && <div><div className="text-muted-foreground">Goods receipts</div>{order.goodsReceiptNotes.map((grn) => <Link key={grn.id} className="mr-3 text-primary hover:underline" href={`/dashboard/purchase/grn/${grn.id}`}>{formatFinancialDocumentNumber(grn.grnFy, grn.grnNo)} ({grn.status})</Link>)}</div>}</CardContent></Card><Card><CardHeader><CardTitle>Totals</CardTitle></CardHeader><CardContent className="space-y-2 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>{money(order.subtotal)}</span></div><div className="flex justify-between"><span>Discount</span><span>- {money(order.discountTotal)}</span></div><div className="flex justify-between"><span>Taxable</span><span>{money(order.taxableTotal)}</span></div><div className="flex justify-between"><span>GST</span><span>{money(order.gstTotal)}</span></div><div className="flex justify-between"><span>Freight</span><span>{money(order.shippingAmount)}</span></div><div className="flex justify-between border-t pt-3 text-lg font-semibold"><span>Grand total</span><span>{money(order.grandTotal)}</span></div></CardContent></Card></div>
  </div>; }
