import assert from "node:assert/strict";
import { ProductSchema } from "../src/lib/validators/dashboard/products/ProductValidator";
import { gasGroupLabel, publishedZones, safeTechnicalDescription } from "../src/lib/products/technical-data";
import { toCatalogProductDetail } from "../src/lib/marketing/catalog";
import { productSchema } from "../src/lib/seo/product";
import { serializeJsonLd } from "../src/components/seo/JsonLd";
import { categoryLandings, matchesLanding } from "../src/lib/seo/categories";
import { legacyProductCandidates } from "../src/lib/seo/legacy-products";
import { z } from "zod";

const ordinary = { name: "FLP/WP Junction Box", flpType: "Ex db IIC T4 Gb", zones: ["Zone-0", "Zone-1", "Zone-2"] };
assert.deepEqual(publishedZones(ordinary), ["Zone-1", "Zone-2"]);
assert.deepEqual(publishedZones({ ...ordinary, flpType: "Flameproof as per IEC:60079-1:2014" }), ["Zone-1", "Zone-2"]);
assert.deepEqual(publishedZones({ ...ordinary, flpType: "Ex da IIC T6 Ga" }), ordinary.zones);
assert.deepEqual(publishedZones({ ...ordinary, name: "NON FLP Flood Light" }), []);
assert.equal(safeTechnicalDescription("Suitable for Zone-0, Zone-1 and Zone-2", ordinary), undefined);
assert.equal(gasGroupLabel("IIB + H2"), "IIB + H2");
assert.equal(gasGroupLabel("IIA, IIB & IIC as per IS/IEC:60079-1"), "IIA/IIB/IIC");
assert(!gasGroupLabel("IIA, IIB").includes("Ex d"));
const request = { ...ordinary, slug: "junction-box", categoryId: "f38cd382-9593-4b6a-a23f-d98bdbb313ea" };
assert(!ProductSchema.safeParse(request).success);
assert(ProductSchema.safeParse({ ...request, zones: ["Zone-1", "Zone-2"] }).success);
assert(ProductSchema.safeParse({ ...request, name: "Non FLP Light", zones: [] }).success);
assert(!ProductSchema.safeExtend({ id: z.uuid() }).safeParse({ ...request, id: request.categoryId }).success);
const product = toCatalogProductDetail({ ...ordinary, slug: "junction-box", protection: "IP-66 as per IS/IEC:60079-1", gasGroup: "IIB + H2", shortDesc: "Suitable for Zone-0", categoryId: request.categoryId, category: { id: request.categoryId, name: "Flameproof Junction Boxes", slug: "flameproof-junction-boxes" }, variants: [{ id: "v1", variant: "4 Way", typeNumber: "EJB-100", sku: "JB-4", images: [], drawings: [] }, { id: "v2", variant: "6 Way", typeNumber: "EJB-100", sku: "JB-6", images: [], drawings: [] }] });
assert.deepEqual(product.zones, ["Zone-1", "Zone-2"]);
assert.equal(product.protection, "IP-66");
assert.equal(product.group, "IIB + H2");
const schema = productSchema(product);
assert.equal(schema["@graph"][0]["@type"], "ProductGroup");
assert(!JSON.stringify(schema).includes("Zone-0"));
assert(!JSON.stringify(schema).includes('"offers"'));
const text = '</script><script>alert("x")</script>';
const serialized = serializeJsonLd({ name: text });
assert(!serialized.includes("</script>"));
assert.equal(JSON.parse(serialized).name, text);
assert.equal(categoryLandings.length, 12);
assert(!matchesLanding({ name: "NON FLP Flood Light", cat: "NON FLP Light" }, categoryLandings.find(item => item.slug === "flameproof-floodlights")!));
assert(legacyProductCandidates("flp-wp-cleanroom-switch-socket").includes("flpwp-clean-room-switch-socket-fitting"));
console.log("PASS: zone publication, approval validation, non-FLP data, restricted gas groups, product variants, safe JSON-LD and category matching.");
